### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by snowe2010** [ezekg/swa-dashboard#3]
Attempting to run a query following along with your example, I get the error: 
```
 swa --from 'DEN' --to 'SEA' --leave-date '02/10/2017' --return-date '02/15/2016' --passengers 2 --individual-deal-price 50 --total-deal-price 110 --interval 5
```

```
C:\Users\Tyler\Dropbox\Programming\git\swa-dashboard\index.js:4
const osmosis = require("osmosis")
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```

**Comment by snowe2010** [comment]
That was on windows 10, on Mac Sierra I get this no matter what command I run


```
swa -h
/Users/tylerthrailkill/Documents/dev/code/play/swa-dashboard/index.js:236
      x: [...this.graphs.outbound.x, now],
          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
```

**Comment by snowe2010** [comment]
Looks like I wasn't using up to date node. Sorry about that!

**Comment by lookatmeimdanny** [comment]
How did you update this?  I just updated node and npm and I'm still getting this error.
