### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by dimdog** [ezekg/swa-dashboard#6]
After running npm link and getting this output:

```
~ npm link
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
|
> libxmljs@0.18.0 install /Users/ben/swa-dashboard/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
  CC(target) Release/obj.target/libxml/vendor/libxml/catalog.o
  CC(target) Release/obj.target/libxml/vendor/libxml/chvalid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/dict.o
  CC(target) Release/obj.target/libxml/vendor/libxml/encoding.o
  CC(target) Release/obj.target/libxml/vendor/libxml/entities.o
  CC(target) Release/obj.target/libxml/vendor/libxml/error.o
  CC(target) Release/obj.target/libxml/vendor/libxml/globals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/hash.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLparser.o
../vendor/libxml/HTMLparser.c:4403:41: warning: missing field 'begin_pos'
      initializer [-Wmissing-field-initializers]
    htmlParserNodeInfo node_info = { 0, };
                                        ^
1 warning generated.
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLtree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/legacy.o
  CC(target) Release/obj.target/libxml/vendor/libxml/list.o
  CC(target) Release/obj.target/libxml/vendor/libxml/parser.o
  CC(target) Release/obj.target/libxml/vendor/libxml/parserInternals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/pattern.o
  CC(target) Release/obj.target/libxml/vendor/libxml/relaxng.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX2.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX.o
  CC(target) Release/obj.target/libxml/vendor/libxml/tree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/threads.o
  CC(target) Release/obj.target/libxml/vendor/libxml/uri.o
  CC(target) Release/obj.target/libxml/vendor/libxml/valid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xinclude.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xlink.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlIO.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmemory.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmodule.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlreader.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlregexp.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlsave.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemas.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemastypes.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlstring.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlunicode.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlwriter.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xpath.o
In file included from ../vendor/libxml/xpath.c:462:
../vendor/libxml/timsort.h:405:65: warning: comparison of integers of different
      signs: 'long long' and 'const size_t' (aka 'const unsigned long')
      [-Wsign-compare]
    if ((stack_curr == 2) && (stack[0].length + stack[1].length == size)) {
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~
In file included from ../vendor/libxml/xpath.c:476:
../vendor/libxml/trionan.c:194:1: warning: unused function
      'trio_is_special_quantity' [-Wunused-function]
trio_is_special_quantity
^
../vendor/libxml/trionan.c:218:1: warning: unused function 'trio_is_negative'
      [-Wunused-function]
trio_is_negative
^
3 warnings generated.
  CC(target) Release/obj.target/libxml/vendor/libxml/xpointer.o
  LIBTOOL-STATIC Release/xml.a
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
  CXX(target) Release/obj.target/xmljs/src/xml_attribute.o
  CXX(target) Release/obj.target/xmljs/src/xml_document.o
../src/xml_document.cc:424:26: warning: unused variable
      'excludeImpliedElementsOpt' [-Wunused-variable]
    v8::Local<v8::Value> excludeImpliedElementsOpt = options->Get(
                         ^
1 warning generated.
  CXX(target) Release/obj.target/xmljs/src/xml_element.o
  CXX(target) Release/obj.target/xmljs/src/xml_comment.o
  CXX(target) Release/obj.target/xmljs/src/xml_namespace.o
  CXX(target) Release/obj.target/xmljs/src/xml_node.o
  CXX(target) Release/obj.target/xmljs/src/xml_sax_parser.o
  CXX(target) Release/obj.target/xmljs/src/xml_syntax_error.o
  CXX(target) Release/obj.target/xmljs/src/xml_text.o
  CXX(target) Release/obj.target/xmljs/src/xml_xpath_context.o
  SOLINK(target) Release/xmljs.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
date-format@0.0.2 node_modules/date-format

chalk-rainbow@1.0.0 node_modules/chalk-rainbow

airports@1.0.0 node_modules/airports

blessed@0.1.81 node_modules/blessed

chalk@1.1.3 node_modules/chalk
├── supports-color@2.0.0
├── escape-string-regexp@1.0.5
├── ansi-styles@2.2.1
├── strip-ansi@3.0.1 (ansi-regex@2.0.0)
└── has-ansi@2.0.0 (ansi-regex@2.0.0)

pretty-ms@2.1.0 node_modules/pretty-ms
├── plur@1.0.0
├── parse-ms@1.0.1
└── is-finite@1.0.2 (number-is-nan@1.0.1)

blessed-contrib@3.5.5 node_modules/blessed-contrib
├── ansi-term@0.0.2
├── memorystream@0.3.1
├── x256@0.0.2
├── term-canvas@0.0.5
├── strip-ansi@3.0.1 (ansi-regex@2.0.0)
├── marked@0.3.6
├── sparkline@0.1.2 (here@0.0.2, nopt@2.1.2)
├── memory-streams@0.1.0 (readable-stream@1.0.34)
├── drawille-canvas-blessed-contrib@0.1.3 (bresenham@0.0.3, drawille-blessed-contrib@1.0.0, gl-matrix@2.3.2)
├── map-canvas@0.1.5 (xml2js@0.4.17)
├── picture-tube@0.0.4 (buffers@0.1.1, charm@0.1.2, png-js@0.1.1, optimist@0.3.7, request@2.9.203, event-stream@0.9.8)
├── request@2.79.0 (tunnel-agent@0.4.3, aws-sign2@0.6.0, forever-agent@0.6.1, oauth-sign@0.8.2, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, aws4@1.5.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, uuid@3.0.1, qs@6.3.0, combined-stream@1.0.5, mime-types@2.1.13, tough-cookie@2.3.2, form-data@2.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── marked-terminal@1.7.0 (lodash.assign@4.2.0, node-emoji@1.4.3, cli-table@0.3.1, cardinal@1.0.0)
└── lodash@4.17.4

twilio@2.11.1 node_modules/twilio
├── string.prototype.startswith@0.2.0
├── underscore@1.8.3
├── deprecate@0.1.0
├── scmp@0.0.3
├── q@0.9.7
├── jsonwebtoken@5.4.1 (ms@0.7.2, jws@3.1.4)
└── request@2.74.0 (aws-sign2@0.6.0, forever-agent@0.6.1, is-typedarray@1.0.0, caseless@0.11.0, tunnel-agent@0.4.3, oauth-sign@0.8.2, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, aws4@1.5.0, extend@3.0.0, node-uuid@1.4.7, qs@6.2.1, combined-stream@1.0.5, mime-types@2.1.13, tough-cookie@2.3.2, hawk@3.1.3, bl@1.1.2, http-signature@1.1.1, har-validator@2.0.6, form-data@1.0.1)

osmosis@1.1.2 node_modules/osmosis
├── needle@1.3.0 (debug@2.6.0, iconv-lite@0.4.15)
└── libxmljs-dom@0.0.8 (css2xpath@0.0.1, libxmljs@0.18.0)
```

using either `swa` or `node index.js` I get a syntaxError:

```
~/swa-dashboard master node index.js --from 'SFO' --to 'LAX' --leave-date '03/01/2016' --return-date '03/07/2016' --passengers 2 --interval 5
/Users/ben/swa-dashboard/index.js:236
      x: [...this.graphs.outbound.x, now],
          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```

**Comment by ezekg** [comment]
You're using an old version of Node that doesn't support the ES6 syntax. See https://github.com/ezekg/swa-dashboard/issues/3#issuecomment-268444967.
